version: '3'
services:
  client:
    build: ./open-hotel-client
    command: 'yarn --cwd packages/client dev --mode=docker'
    ports:
      - '8081:8080'
    volumes:
      - ./open-hotel-client:/code
      - /code/node_modules
    networks:
      openHotel: {}
  
  emulator:
    build: ./orion-emulator
    working_dir: '/sirius/packages/emulator'
    command: 'yarn dev'
    ports:
      - '3000:3000'
      - '65432:65432'
      - '9229:9229'
      - '9229:9229/udp'
    volumes:
      - ./orion-emulator:/sirius
      - /sirius/node_modules
    networks:
      openHotel: {}

  arango:
    image: arangodb/arangodb:3.5.1
    volumes:
      - ./docker/db:/var/lib/arangodb3
    ports:
      - '8529:8529'
    environment:
      - ARANGO_ROOT_PASSWORD=12345
    networks:
      openHotel: {}

  nginx:
      container_name: nginx
      restart: always
      image: nginx
      depends_on:
        - client
        - emulator
      volumes:
          - ./nginx:/var/www/html
          - ./nginx/log:/var/log/nginx
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - '44113:44113'
          - '1234:1234'
          - "8080:80"
          - "443:443"
      networks:
        openHotel: {}
networks:
  openHotel: {}
