version: '3'
services:
  client:
    build: ./open-hotel-client
    command: 'yarn --cwd packages/client dev --mode=docker'
    ports:
      - '8081:8080'
    volumes:
      - ./open-hotel-client:/code
      - /code/node_modules
    networks:
      openHotel: {}
  emulator:
    build: ./orion-emulator
    working_dir: '/sirius'
    command: 'yarn start:dev'
    ports:
      - '3000:3000'
    volumes:
      - ./orion-emulator:/sirius
      - /sirius/node_modules
    networks:
      openHotel: {}

  mongo:
    image: mongo
    volumes:
      - ./docker/db:/data/db
    ports:
      - '27017:27017'
    networks:
      openHotel: {}

  nginx:
      container_name: nginx
      restart: always
      image: nginx
      depends_on:
        - client
        - emulator
      volumes:
          - ./nginx:/var/www/html
          - ./nginx/log:/var/log/nginx
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - "8080:80"
          - "443:443"
      networks:
        openHotel: {}
networks:
  openHotel: {}
